### PR TITLE
feat: adding docs for env vars

### LINKED ISSUE #6: List all environment variables across sub-projects in the "Environment Variables" page
In the previous documentation, [we used to have a page that listed all of the environment variables across all the Reaction sub-projects](https://docs.reactioncommerce.com/docs/3.0.0/environment-variables#docsNav).

We need a similar page on the new docs, so that newcomers know exactly what each environment variable does and whether or not it's required for their use case.

### PR DESCRIPTION
**Pull request by Akarshit**
Closes: #6 

This PR adds the list of environment variable to the docs.

### CODE REVIEW

**Comment by ecormany** [comment]
This content looks largely unchanged from the previous docs site. We should take some time to edit it, focusing on:

- making sure all the listed variables are supported in the current and soon-to-be-released version (and none are missing)
- including any relevant information from the 3rd and 4th columns of the old table, rather than simply deleting them
- making sure all prose is clean and fits the style of `/developer`
- deciding whether the information best fits in the Fundamentals doc or as a separate doc

We can work here within the PR or in some other venue (if it's more convenient) and then import our work.

**Comment by loan-laux** [comment]
Just making a quick note not to forget `REACTION_SHOULD_ENCODE_IDS`, which was the discovery that sparked the need for this list of env variables.

**Comment by Akarshit** [comment]
@ecormany 
1. I went through the doc and can verify all the env are present for the `v4.0` release.
2. As we work on the deployment guide, we can provide more information on what ENV variables need to set in production.
3. I can work on the prose, if you let me know what doesn't sound right.
4. I am not sure what the criteria for fundamental doc vs other doc is.

**Comment by Akarshit** [comment]
Update on this one, we have a Google doc that's being processed and would be soon merged back into this PR.

**Review by spencern — APPROVED** [review]
Thanks for getting this put together! While there are still a few discussions going on in the background, I think it's best that we merge this and evolve as new decisions are made. This is an important bit of documentation and the docs will be better with this PR merged.

**Pull request merged**
